"""baseline — the current model schema

Adopting Alembic on an existing schema: revision 0001 creates every table the
ORM defines, dialect-correctly (JSONB on Postgres / JSON on SQLite, etc.), by
applying Base.metadata. Future revisions are normal autogenerated diffs on top.

Revision ID: 0001_baseline
Revises:
Create Date: 2026-07-09
"""

from alembic import op

revision = "0001_baseline"
down_revision = None
branch_labels = None
depends_on = None


def _metadata():
    from app.core.database import Base, import_all_models

    import_all_models()
    return Base.metadata


def upgrade() -> None:
    _metadata().create_all(op.get_bind())


def downgrade() -> None:
    _metadata().drop_all(op.get_bind())
